name: Build & Release (Windows)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MSYS2 (MinGW-w64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            base-devel
            mingw-w64-x86_64-gcc
            zip

      - name: Build .exe
        shell: msys2 {0}
        run: |
          gcc -O2 -Wall -municode -static -o PowerClose.exe *.c -luser32 -lkernel32
          ./PowerClose.exe --help || true
          zip PowerClose_windows.zip PowerClose.exe

      - name: Upload artifact (for CI runs)
        uses: actions/upload-artifact@v4
        with:
          name: PowerClose_windows
          path: PowerClose_windows.zip

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: PowerClose_windows
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: PowerClose_windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
