name: Build & Release Windows EXE (MinGW + Icon)

on:
  release:
    types: [published]         # when you click “Publish release” in GUI
  push:
    tags:
      - "v*"                   # or when you push a tag like v1.0.0
  workflow_dispatch:           # optional manual run from Actions tab

permissions:
  contents: write              # required to upload to Releases

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MSYS2 (MinGW-w64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-binutils
            zip

      - name: Build EXE (embed icon + link COM/Shell/UUID)
        shell: msys2 {0}
        run: |
          # Build resource from RC (uses powerclose.ico)
          windres -i powerclose.rc -o powerclose_res.o

          # Compile & link; remove -static if it causes CRT issues
          gcc -O2 -Wall -s -municode -static -o PowerClose.exe *.c powerclose_res.o \
              -luser32 -lkernel32 -lole32 -lshell32 -luuid

          # Package: include EXE, and include ICO in the ZIP for convenience
          if [ -f powerclose.ico ]; then
            zip PowerClose_windows.zip PowerClose.exe powerclose.ico
          else
            zip PowerClose_windows.zip PowerClose.exe
          fi

      - name: Upload artifact (for CI debugging)
        uses: actions/upload-artifact@v4
        with:
          name: PowerClose_windows
          path: PowerClose_windows.zip

  release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: PowerClose_windows
          path: .

      # If triggered by a tag push (e.g., v1.0.0), create/update that tag's release
      - name: Create/Update Release for tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: PowerClose_windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # If triggered by publishing a release in the GUI, attach to that release
      - name: Attach asset to published Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: PowerClose_windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
